[package]
name = "speex-safe"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/actioninja/speex-rs/tree/master/speex-safe"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
speex-sys = { path = "speex-sys" }